### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by dev-shah-2204** [thomson008/CSGO-Bot#1]
Can you explain the database structure? I'm trying to add csgo features to my discord bot.
`from replit import db` 
What does the db store?

**Comment by thomson008** [comment]
Hi, sorry for a late reply, I was really busy last few weeks :)
The database holds key-value pairs, where keys are Discord usernames and values are their corresponding Steam IDs.
When you ask the bot for your CS:GO stats, it will first check if it has your Discord name in the database, and if not, it should ask you for it. I'm using a Replit database, you can see how it works [here](https://replit.com/@thomson0081/CSGO-Bot).
