### ISSUE TITLE
Privacy error

### ISSUE THREAD

**Issue by dev-shah-2204** [thomson008/CSGO-Bot#2]
All the details are public but the bot sends this message:

`Oops, looks like I don't have access to your Steam data. You have to set it to 'Public' first. `

**Comment by thomson008** [comment]
I'm afraid I'm not able to replicate this error. Are you sure you have all the details set like this on Steam?
![image](https://user-images.githubusercontent.com/49678281/126065170-c7f35b57-cd56-4214-aa54-7f773ca3c098.png)

**Comment by dev-shah-2204** [comment]
yes, all my details are public. I even tried it with other accounts. It might have been some other problem
